package tp1.api;

import java.util.Set;

import tp1.api.engine.AbstractSpreadsheet;
import tp1.server.resources.SpreadsheetResource;
import tp1.util.CellRange;


/**
 * Represents a spreadsheet.
 */
public class Spreadsheet implements AbstractSpreadsheet {
	// id of the sheet - generated by the system
	private String sheetId;
	// id of the owner
	private String owner;
	// URL of the sheet (REST endpoint) - generated by the system
	private String sheetURL;
	// number of the lines and columns
	private int rows, columns;
	// set of users with which ths sheet is shared
	
	private Set<String> sharedWith;
	
	// raw contents of the sheet
	private String[][] rawValues;
	
	public Spreadsheet() {	
	}

	public Spreadsheet(String sheetId, String owner, String sheetURL, int rows, int columns, Set<String> sharedWith, String[][] rawValues) {
		super();
		this.sheetId = sheetId;
		this.owner = owner;
		this.sheetURL = sheetURL;
		this.rows = rows;
		this.columns = columns;
		this.sharedWith = sharedWith;
		this.rawValues = rawValues;
	}

	public Spreadsheet(Spreadsheet s, String sheetId, String domainId) {
		super();
		this.sheetId = sheetId;
		this.owner = s.owner;
		this.sheetURL = domainId+"#id#"+sheetId;
		this.rows = s.rows;
		this.columns = s.columns;
		this.sharedWith = s.sharedWith;
		this.rawValues = s.rawValues;
	}

	public String getSheetId() {
		return sheetId;
	}


	public void setSheetId(String sheetId) {
		this.sheetId = sheetId;
	}


	public String getOwner() {
		return owner;
	}


	public void setOwner(String owner) {
		this.owner = owner;
	}


	public String getSheetURL() {
		return sheetURL;
	}


	public void setSheetURL(String sheetURL) {
		this.sheetURL = sheetURL;
	}


	public int getRows() {
		return rows;
	}


	public void setRows(int rows) {
		this.rows = rows;
	}


	public int getColumns() {
		return columns;
	}


	public void setColumns(int columns) {
		this.columns = columns;
	}

	public Set<String> getSharedWith() {
		return sharedWith;
	}


	public void setSharedWith(Set<String> sharedWith) {
		this.sharedWith = sharedWith;
	}


	public String[][] getRawValues() {
		return rawValues;
	}

	public void setRawValues(String[][] rawValues) {
		this.rawValues = rawValues;
	}

	/**
	 * Updates the raw value of cell, given the cell name (e.g. A1).
	 * @param cell  - the cell being updated.
	 * @param value the new raw value.
	 */
	public void placeCellRawValue(String cell, String value) {
		var r = new CellRange( cell + ":A1");
		rawValues[r.topRow][ r.topCol] = value;
	}
	
	/**
	 * Updates the raw value of cell, given the row and col indices.
	 * @param row  - the row index of the cell being updated.
	 * @param col  - the column index of the cell being updated.
	 * @param value the new raw value.
	 */
	@Deprecated
	public void placeCellRawValue(int row, int col, String value) {
		rawValues[row][ col] = value;
	}
	
	/**
	 * Gets the raw value of a cell, given its index coordinates.
	 * @param row - the row index.
	 * @param col - the column index.
	 * @return the raw value of the cell.
	 */
	public String extractCellRawValue(int row, int col) {
		return rawValues[row][col];
	}

	public String extractOwnerDomain() {
		return owner.split("@")[1];
	}

	@Override
	public int rows() {
		return rows;
	}

	@Override
	public int columns() {
		return columns;
	}

	@Override
	public String sheetId() {
		return sheetId;
	}

	@Override
	public String cellRawValue(int row, int col) {
		return rawValues[row][col];
	}

	@Override
	public String[][] rangeValues(String sheetURL, String range) {
		try {
			String[] parts = sheetURL.split("#id#");
			String domainId = parts[0];
			String otherSheetId = parts[1];
			return SpreadsheetResource.getRemoteSpreadsheetClient(domainId).getReferencedSpreadsheetValues(otherSheetId, owner, range);
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}
}
